# TYPE  DATABASE        USER            ADDRESS                 METHOD
# Conexiones Unix socket (para healthcheck interno)
local   all             all                                     trust

# Conexiones SSL obligatorias con autenticación criptográfica de certificado de cliente (mTLS)
# clientcert=verify-full verifica la CA y que el CN del certificado coincida con el usuario de conexión
hostssl all             all             127.0.0.1/32            cert clientcert=verify-full
hostssl all             all             all                     cert clientcert=verify-full
