-- Script de inicializacion de la db

-- =============================================
-- EXTENSIONES
-- =============================================
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- =============================================
-- CREACIÓN DE LAS TABLAS
-- =============================================
CREATE TABLE IF NOT EXISTS public.flyway_schema_history (
	installed_rank int4 NOT NULL,
	"version" varchar(50) NULL,
	description varchar(200) NOT NULL,
	"type" varchar(20) NOT NULL,
	script varchar(1000) NOT NULL,
	checksum int4 NULL,
	installed_by varchar(100) NOT NULL,
	installed_on timestamp DEFAULT now() NOT NULL,
	execution_time int4 NOT NULL,
	success bool NOT NULL,
	CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);
CREATE INDEX IF NOT EXISTS flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);

CREATE TABLE IF NOT EXISTS public.infrastructure_credentials (
	id int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	user_id int8 NOT NULL,
	wazuh_ip varchar(255) NULL,
	wazuh_password varchar(255) NULL,
	wazuh_user varchar(255) NULL,
	CONSTRAINT infrastructure_credentials_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.report_signatures (
	id int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	digital_signature text NOT NULL,
	report_name varchar(255) NULL,
	sha256_hash varchar(64) NOT NULL,
	signed_at timestamp(6) NULL,
	CONSTRAINT report_signatures_pkey PRIMARY KEY (id),
	CONSTRAINT uk1a2kvq59gmmliwnv1dsmvkoxl UNIQUE (sha256_hash)
);

CREATE TABLE IF NOT EXISTS public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	created_at timestamp(6) NULL,
	email varchar(255) NOT NULL,
	first_name varchar(255) NOT NULL,
	maternal_last_name varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	paternal_last_name varchar(255) NOT NULL,
	"role" varchar(255) NOT NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- vulnerabilities: PK se crea sin detection_time para poder crear hypertable
CREATE TABLE IF NOT EXISTS public.vulnerabilities (
	id int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	agent_group varchar(255) NULL,
	agent_id varchar(255) NULL,
	agent_name varchar(255) NULL,
	cve varchar(255) NOT NULL,
	cvss3_score float8 NULL,
	description text NULL,
	detection_time timestamp(6) NULL,
	last_sync timestamp(6) NULL,
	package_name varchar(255) NULL,
	package_version varchar(255) NULL,
	resolved_at timestamp(6) NULL,
	severity varchar(255) NULL,
	status varchar(255) NULL,
	title varchar(255) NULL
);

-- vulnerability_snapshots: PK compuesta incluye snapshot_date para hypertable
CREATE TABLE IF NOT EXISTS public.vulnerability_snapshots (
	id int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	agent_id varchar(255) NOT NULL,
	agent_name varchar(255) NULL,
	critical_count int4 NOT NULL,
	high_count int4 NOT NULL,
	low_count int4 NOT NULL,
	medium_count int4 NOT NULL,
	snapshot_date timestamp(6) NOT NULL,
	total_count int4 NOT NULL,
	CONSTRAINT vulnerability_snapshots_pkey PRIMARY KEY (id, snapshot_date)
);

-- =============================================
-- HYPER TABLES (TimescaleDB)
-- =============================================
-- vulnerabilities: particionado por detection_time, 7 days por defecto
SELECT create_hypertable('vulnerabilities', 'detection_time',
    chunk_time_interval => INTERVAL '7 days',
    if_not_exists => TRUE);

-- Agregar PK compuesto con detection_time (requerido por hypertable)
ALTER TABLE vulnerabilities ADD PRIMARY KEY (id, detection_time);

-- vulnerability_snapshots: particionado por snapshot_date, 1 day
SELECT create_hypertable('vulnerability_snapshots', 'snapshot_date',
    chunk_time_interval => INTERVAL '1 day',
    if_not_exists => TRUE);

-- =============================================
-- COMPRESIÓN (TimescaleDB)
-- =============================================
ALTER TABLE vulnerabilities SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'agent_id'
);
SELECT add_compression_policy('vulnerabilities', INTERVAL '7 days', if_not_exists => TRUE);

-- =============================================
-- ÍNDICES DE RENDIMIENTO (V2)
-- =============================================

-- Upsert lookup: WazuhService.processAndSaveBatch()
CREATE INDEX IF NOT EXISTS idx_vuln_sync_lookup
    ON vulnerabilities (cve, agent_id, package_name);

-- Dashboard/charts: severity distribution + agent filter
CREATE INDEX IF NOT EXISTS idx_vuln_severity_agent
    ON vulnerabilities (severity, agent_id);

-- Mark and Sweep: bulk update old vulns to Resolved
CREATE INDEX IF NOT EXISTS idx_vuln_last_sync_status
    ON vulnerabilities (last_sync, status);

-- Date range filters: dashboard date range
CREATE INDEX IF NOT EXISTS idx_vuln_detection_time
    ON vulnerabilities (detection_time);

-- High-priority filter: partial index for critical/high
CREATE INDEX IF NOT EXISTS idx_vuln_high_priority
    ON vulnerabilities (severity, agent_id)
    WHERE LOWER(TRIM(COALESCE(severity, ''))) IN ('critical', 'high', 'alta', 'crítica', 'critica');

-- Snapshot query: latest snapshot per agent
CREATE INDEX IF NOT EXISTS idx_vsnap_agent_date
    ON vulnerability_snapshots (agent_id, snapshot_date DESC);

-- Free-text search: trigram indexes
CREATE INDEX IF NOT EXISTS idx_vuln_cve_trgm
    ON vulnerabilities USING gin (cve gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_vuln_package_name_trgm
    ON vulnerabilities USING gin (package_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_vuln_agent_name_trgm
    ON vulnerabilities USING gin (agent_name gin_trgm_ops);

-- vulnerability_snapshots snapshot_date index
CREATE INDEX IF NOT EXISTS vulnerability_snapshots_snapshot_date_idx
    ON public.vulnerability_snapshots USING btree (snapshot_date DESC);

-- =============================================
-- PROCEDIMIENTOS ALMACENADOS
-- =============================================
CREATE OR REPLACE FUNCTION sp_get_vulnerabilities(
    p_severity VARCHAR DEFAULT NULL,
    p_agent_id VARCHAR DEFAULT NULL,
    p_status VARCHAR DEFAULT NULL,
    p_start_date TIMESTAMP DEFAULT NULL,
    p_end_date TIMESTAMP DEFAULT NULL,
    p_min_cvss DOUBLE PRECISION DEFAULT NULL,
    p_max_cvss DOUBLE PRECISION DEFAULT NULL,
    p_cve VARCHAR DEFAULT NULL,
    p_package_name VARCHAR DEFAULT NULL,
    p_limit INT DEFAULT NULL,
    p_offset INT DEFAULT NULL
)
RETURNS SETOF vulnerabilities AS $$
BEGIN
    RETURN QUERY
    SELECT v.*
    FROM vulnerabilities v
    WHERE 
        (p_severity IS NULL OR v.severity = p_severity)
        AND (p_agent_id IS NULL OR v.agent_id = p_agent_id)
        AND (p_status IS NULL OR v.status = p_status)
        AND (p_start_date IS NULL OR v.detection_time >= p_start_date)
        AND (p_end_date IS NULL OR v.detection_time <= p_end_date)
        AND (p_min_cvss IS NULL OR v.cvss3_score >= p_min_cvss)
        AND (p_max_cvss IS NULL OR v.cvss3_score <= p_max_cvss)
        AND (p_cve IS NULL OR v.cve = p_cve)
        AND (p_package_name IS NULL OR v.package_name = p_package_name)
    ORDER BY v.id ASC
    LIMIT COALESCE(p_limit, 20)
    OFFSET COALESCE(p_offset, 0);
END;
$$ LANGUAGE plpgsql;

-- VISTAS MATERIALIZADAS
CREATE MATERIALIZED VIEW public.mv_vulnerabilities_severities AS
SELECT DISTINCT severity FROM public.vulnerabilities WHERE severity IS NOT NULL;
CREATE UNIQUE INDEX idx_mv_severities ON public.mv_vulnerabilities_severities (severity);

CREATE MATERIALIZED VIEW public.mv_vulnerabilities_status AS
SELECT DISTINCT status FROM public.vulnerabilities WHERE status IS NOT NULL;
CREATE UNIQUE INDEX idx_mv_status ON public.mv_vulnerabilities_status (status);

CREATE MATERIALIZED VIEW public.mv_vulnerabilities_groups AS
SELECT DISTINCT agent_group FROM public.vulnerabilities WHERE agent_group IS NOT NULL;
CREATE UNIQUE INDEX idx_mv_groups ON public.mv_vulnerabilities_groups (agent_group);

CREATE MATERIALIZED VIEW public.mv_vulnerabilities_packages AS
SELECT DISTINCT package_name FROM public.vulnerabilities WHERE package_name IS NOT NULL;
CREATE UNIQUE INDEX idx_mv_packages ON public.mv_vulnerabilities_packages (package_name);
